# This workflow will run tests using node and then publish a package to GitHub Container Registry and Docker Hub Regitry when a pushed into main branches
# This file was contributed by ysenih@erpya.com from ERP Consultores y Asociados, C.A

name: Push Main Branches

on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches:
      - main
      - master
      - master-i18n
      - cutomer/*
  release:
    types: 
      - published

jobs:

  # Publish docker image in Github Container Registry to application
    # Build dist application ADVue-Theme-Pos
  build-app:
    name: Build dist ADVue-Theme-Pos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Node configuration
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Compress files for application dist
        uses: TheDoctor0/zip-release@0.6.0
        with:
          type: 'zip'
          filename: 'ADVue-Theme-Pos.zip'
          path: './'
          exclusions: './dist ./docker ./docs'

      - name: Upload app as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ADVue-Theme-Pos        
          path: ./ADVue-Theme-Pos.zip


  # Publish docker image in Github Container Registry to application
  push-imame-ghcr:
    name: Push Docker image to GitHub Container
    needs:
      - build-app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Download build dist app
        uses: actions/download-artifact@v2
        with:
          name: ADVue-Theme-Pos

      - name: Uncompress dist files
        run: unzip ADVue-Theme-Pos.zip -d dist-app

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Lower Case to owner and repository
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
          echo "REPO_LC=${NAME,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
          NAME: '${{ github.event.repository.name }}'

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.8

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:${{ steps.branch-name.outputs.current_branch }}
            ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

